name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-windows-gnu
            prefix: zig-out/x86_64-windows-gnu
          - os: ubuntu-latest
            target: aarch64-windows-gnu
            prefix: zig-out/aarch64-windows-gnu
          - os: ubuntu-latest
            target: x86_64-linux-musl
            prefix: zig-out/x86_64-linux-musl
          - os: ubuntu-latest
            target: aarch64-linux-musl
            prefix: zig-out/aarch64-linux-musl
          - os: macos-latest
            target: aarch64-macos
            prefix: zig-out/aarch64-macos
          - os: macos-latest
            target: x86_64-macos
            prefix: zig-out/x86_64-macos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Build
        run: zig build -Dtarget=${{ matrix.target }} --prefix ${{ matrix.prefix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.prefix }}
